---
# file: tasks/use-yum.yml
# Configure Node.js from YUM repository.
# @see https://github.com/nodesource/distributions

- name: Add Nodesource repositories for Node.js.
  yum:
    name: "https://rpm.nodesource.com/pub_{{ nodejs_version }}/el/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/nodesource-release-el{{ ansible_distribution_major_version }}-1.noarch.rpm"
    state: present

- name: Ensure Node.js and npm are installed.
  yum: 
    name: "{{ nodejs_pkg }}"
    state: present 
    enablerepo: "nodesource"

