---
# file: tasks/use-yum.yml
# Configure Node.js from APT repository.
# @see https://github.com/nodesource/distributions
#
- name: Add nodejs repository key
  apt_key: 
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add nodejs repo
  apt_repository: 
    repo: "deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release}} main"
    #repo='deb https://deb.nodesource.com/node_4.x trusty main'
    state: present

- name: Install nodejs
  apt: 
    name: "{{ nodejs_pkg }}"
    state: installed
    update_cache: true
